apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIP
  selector:
    app: kubernetes-simple-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  externalIPs:
  - 192.168.55.220
