apiVersion: v1
kind: Service
metadata:
  name: headless-simple
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: kubernetes-simple-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
