apiVersion: v1
kind: ReplicationController
metadata:
  name: demorc
  labels:
    app: web
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: demopod
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  selector:
    app: web
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  type: NodePort

