apiVersion: v1
kind: ReplicationController
metadata:
  name: demorc
  labels:
    app: web
spec:
  replicas: 10
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: demopod
        image: nginx
        ports:
        - containerPort: 80
