apiVersion: v1
kind: Pod
metadata:
  name: demopod3
  labels:
    app: nginx
spec:
  imagePullSecrets:
    - name: registry-secret
  containers:
  - name: demopod
    image: nginx
    ports: 
    - containerPort: 80
#    resources:
#      requests:
#        cpu: 250m
#  nodeSelector:
#    tier: frontend

