all:
  hosts:
    node1:
      ansible_host: 192.168.55.215
      ip: 192.168.55.215
      access_ip: 192.168.55.215
    node2:
      ansible_host: 192.168.55.216
      ip: 192.168.55.216
      access_ip: 192.168.55.216
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
