apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-2
  name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-2
    spec:
      serviceAccountName: anyuid-sa
      containers:
      - image: docker.io/library/nginx
        name: nginx-2
        ports:
        - containerPort: 80

