apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-2
  name: nginx-2
spec:
  ports:
  - name: 82-80
    port: 82
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-2
  type: ClusterIP
status:
  loadBalancer: {}
